### ISSUE TITLE
Is is compatible with Redux 6?

### ISSUE THREAD

**Issue by zomars** [TarikHuber/firekit-provider#1]
I've seend there some breaking changes, and it would be nice to upgrade.

**Comment by zomars** [comment]
[Here's some useful information](https://github.com/reduxjs/react-redux/issues/1104), and 
[here's how `connected-react-router`did it](https://github.com/supasate/connected-react-router/pull/191/files#diff-e6f81a9d8df4fb4d787121a242ea6bf1).

**Comment by TarikHuber** [comment]
Hi @zomars,
It works with react 6.0 and it uses the new Context API. Do you have problems with it?
We are using it in our demo project https://github.com/TarikHuber/react-most-wanted with all dependencies up to date. We made the migration as soon the Redux version was released.

**Comment by zomars** [comment]
I can see that you made commits about it, but haven't tagged any release yet. I think that's why the NPM version is still outdated.

**Comment by TarikHuber** [comment]
The latest version with the react 6.0 updates is 1.0.1 witch is published to npm. When you make a update to the package you have the latest code. Do you have any issues or errors to report? Maybe there is a bug with the lates code that I don't know of.

**Comment by TarikHuber** [comment]
Now the tags are also pushed but the published version on npm is still the latest one 1.0.1

**Comment by zomars** [comment]
Thanks for the response, I'll test it out and report back.
